---
abstract: unknown
author:
  - 'fu kai <iakuf@163.com>'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-DirectoryQueue
no_index:
  directory:
    - t
    - inc
requires:
  Directory::Queue: 0
  Mojolicious: 4.90
  POSIX: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
